name: flutter_gcaptcha_v3
description: Implementation of Google reCAPTCHA v3 for Flutter (IOS/Android)
version: 2.1.1+1
repository: https://github.com/basnetjiten/flutter_gcaptcha_v3

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.11.0

  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  #functional programmings
  dartz: ^0.10.1

flutter:
  uses-material-design: true
  assets:
    - packages/flutter_gcaptcha_v3/assets/index.html
